In [1]:
from torch.utils.data import SubsetRandomSampler
from torch.utils.data.dataset import Dataset, Subset
from torch.utils.data.dataloader import DataLoader

In [2]:
class DummyDataset(Dataset):
	def __init__(self, size: int):
		super().__init__()
		self.size = size

	def __getitem__(self, index: int) -> int:
		return index

	def __len__(self) -> int:
		return self.size

In [3]:
ds = DummyDataset(100)
indices = list(range(30))

In [4]:
sampler = SubsetRandomSampler(indices)
loader = DataLoader(ds, batch_size=10, sampler=sampler)

In [5]:
for item in loader:
	print(item)

tensor([10,  9, 25,  2,  4, 13, 22, 14, 19,  8])
tensor([ 0, 27, 21,  7, 11,  3, 20, 29, 12,  5])
tensor([23,  6,  1, 28, 24, 18, 16, 15, 26, 17])


In [6]:
sub_ds = Subset(ds, indices)
loader_2 = DataLoader(sub_ds, batch_size=10, shuffle=True)

In [7]:
for item in loader:
	print(item)

tensor([18, 28, 25,  4,  0,  8,  9, 16, 13, 29])
tensor([ 5,  6, 23, 20, 27,  2,  1, 19, 10, 22])
tensor([17,  7, 21, 11, 15, 24, 12,  3, 26, 14])


In [8]:
print("Done")

Done
